task #2787:- multiple device id support
tekdi/teachers-app pull request #549
Opened 2024-12-25 19:27 UTC by shreyas1434shinde

2024-12-26 13:37 UTC, itsvick requested changes

2024-12-26 13:37 UTC, itsvick commented on src/components/Header.tsx
> +    const userResponse = await getUserId();
@shreyas1434shinde are u calling api for getting user id?

2024-12-26 13:37 UTC, itsvick commented on src/components/Header.tsx
> +          tenantId: userResponse?.tenantData[0]?.tenantId,
@shreyas1434shinde just use the axiosInstance with post method instead of manually adding headers here

2024-12-26 17:15 UTC, shreyas1434shinde commented on src/components/Header.tsx
> +          tenantId: userResponse?.tenantData[0]?.tenantId,
resolved

2024-12-30 09:05 UTC, itsvick commented on src/components/PlannedSession.tsx
> +                      const deviceId = response?.result?.userDetails
@shreyas1434shinde can u check this `const deviceId = response?.result?.userDetails
  ?.flatMap((device: { deviceId?: string | null }) => device.deviceId || [])
  .filter(Boolean);`

2024-12-30 09:06 UTC, itsvick commented on src/components/SessionCard.tsx
> +          .filter((id: any) => id !== null).flat();;
`const deviceIds = response.result.userDetails
  .filter((user: { role: Role; deviceId?: string | null }) =>
    [Role.TEACHER, Role.STUDENT].includes(user.role)
  )
  .flatMap((user) => user.deviceId || []);`

@shreyas1434shinde

2024-12-30 09:24 UTC, merged