Isuue #PS-2909 & PS-2907   : Show subtopics for topics which has same name in the course-planner and multi-select options for topic
tekdi/teachers-app pull request #550
Opened 2024-12-26 09:14 UTC by suvarnakale

2024-12-26 13:40 UTC, itsvick requested changes

2024-12-26 13:40 UTC, itsvick commented on src/pages/centers/[cohortId]/index.tsx
> +          // limit: 20,
@suvarnakale i think this code has been removed by @shreyas1434shinde please check once and remove it, if not required

2024-12-30 09:09 UTC, itsvick commented on src/components/TopicDetails.tsx
> +          router.push(
@suvarnakale As `filteredData?.[0]?.identifier` used in both the cases can u add one more if condition on top of it... for additional check... u can remove `?.` operator from below statements then

2024-12-30 09:10 UTC, itsvick commented on src/pages/centers/[cohortId]/events/[date]/index.tsx
> +              if (event?.metadata?.type === 'planned') {
@suvarnakale can u add `planned` and `extra`, session in enum... apply it everywhere wherever applicable

2024-12-30 09:19 UTC, suvarnakale commented on src/pages/centers/[cohortId]/index.tsx
> +          // limit: 20,
I have not added it newly.. Its already there.

2024-12-30 09:20 UTC, suvarnakale commented on src/components/TopicDetails.tsx
> +          router.push(
sure

2024-12-30 09:24 UTC, suvarnakale commented on src/pages/centers/[cohortId]/events/[date]/index.tsx
> +              if (event?.metadata?.type === 'planned') {
sure.

2024-12-30 09:39 UTC, merged