Issue #PS-1629 chore: Modified data mapping to display learner's mini-profile based on getUserDetails API
tekdi/teachers-app pull request #98
Opened 2024-08-06 12:59 UTC by Rushikesh-Sonawane99

2024-08-07 05:31 UTC, itsvick requested changes

2024-08-07 05:53 UTC, Rushikesh-Sonawane99 commented on src/components/AttendanceStatusListView.tsx
> +    .map((item) => ({ label: item?.label, value: item?.value }));
@itsvick Reduced complexity and optimised it with for..of loop

2024-08-07 05:53 UTC, Rushikesh-Sonawane99 commented on src/components/LearnerAttendanceStatsListView.tsx
> +    .filter((item) => labelsToExtractForMiniProfile.includes(item.label ?? ''))
@itsvick Added helper function to avoid duplications

2024-08-07 15:26 UTC, itsvick requested changes

2024-08-07 15:26 UTC, itsvick commented on src/components/FormButtons.tsx
>        : isCreatedFacilitator && !isCreateCentered && !isCreatedLearner
@Rushikesh-Sonawane99 simplify this logic

2024-08-07 16:20 UTC, Rushikesh-Sonawane99 commented on src/components/LearnerModal.tsx
> +const modalStyles = (theme: any) => ({
@itsvick exported common style

2024-08-08 05:15 UTC, itsvick commented on src/components/AddFacilitator.tsx
> +            mobile: apiBody?.mobile,
@Rushikesh-Sonawane99 we should not hard code this here, pick the core fields and send here, rest u can pass it in the customFields

2024-08-08 05:17 UTC, itsvick commented on src/components/FormButtons.tsx
> +    : isCreateCentered && !isCreatedFacilitator && !isCreatedLearner
@Rushikesh-Sonawane99 simplify this

2024-08-08 05:20 UTC, itsvick commented on src/utils/app.constant.ts
> +  zIndex: '9999',
@Rushikesh-Sonawane99 style should not be here

2024-08-08 07:12 UTC, merged